kind: Service
apiVersion: v1
metadata:
  name: logstash-service
  namespace: kube-system
spec:
  type: LoadBalancer
  selector:
    app: logstash
  ports:
    - protocol: TCP
      port: 5044
      targetPort: 5044