apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.8.2
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
  http:
    service:
      spec:
        type: LoadBalancer
  # tls:
  #   certificate:
  #     secretName: elasticsearch-es-http-certs-public
  #     selfSignedCertificate:
  #       # add a list of SANs into the self-signed HTTP certificate
  #       subjectAltNames:
  #       - ip: 192.168.1.2
  #       - ip: 192.168.1.3
  #       - dns: elasticsearch-sample.example.com
  #     certificate:
  #       # provide your own certificate
  #       secretName: my-cert