replicas: 1
minimumMasterNodes: 1

ingress:
  enabled: true
  hosts:
    - host: elastic.aws.buildconfes.click #Change the hostname to the one you need
      paths:
        - path: /
  
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
